### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'voice/jumpyEggs0.mp3'

### ISSUE THREAD

**Issue by mrkgoh** [shaongitt/recaptcha-solver#1]
Received this error:

`Traceback (most recent call last):

  File "\\192.168.0.128\home\Drive\vaksin\checkstatus.py", line 92, in <module>
    solver(driver,WebDriverWait,EC,By,NoSuchElementException)

  File "\\192.168.0.128\home\Drive\vaksin\recaptcha_solver.py", line 70, in solver
    urllib.request.urlretrieve(download_link, "voice/" + str(random) + ".mp3")

  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')

FileNotFoundError: [Errno 2] No such file or directory: 'voice/jumpyEggs0.mp3'`

**Comment by mrkgoh** [comment]
Solved it. this helped: https://stackoverflow.com/a/46507796/15339732

**Comment by shaongitbd** [comment]
:)
